* About

#+begin_src sh
  # Run in development.
  clojure -M -m reports-api.core
#+end_src

* Deployment

  Refer to the ~Dockerfile~. You must build the uberjar prior to deployment.
  Refer to the references section below for the deployed app URL.

#+begin_src sh
  # Build the uberjar and deploy to Fly.
  clojure -T:build uber && fly deploy

  # Verify the service is running.
  curl https://patty-reports.fly.dev/api/v1/ping
#+end_src

* API

  Note that JSON keys of the request body can be either in snake_case or in kebab-case, it doesn't matter. All the response JSON keys are in snake_case.

#+begin_src sh
  # Make a request.
  curl http://localhost:8080/api/v1/reports/staff-plan --json @requests/01-base.json | jq

  # Shortcut (see .env/zsh.zsh).
  report staff-plan requests/01-base.json
#+end_src

** Staff plan
*** Minimal request

  Only required properties are provided.

#+begin_src json :tangle requests/01-base.json :mkdirp yes
  {"pay-structure": "Hourly Rate", "base-pay": 90}
#+end_src

*** Pay structure
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Hourly rate

#+begin_src json :tangle requests/02-pay-structure-hourly.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ]
  }
#+end_src

**** Weekly salary

#+begin_src json :tangle requests/03-pay-structure-weekly.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Weekly Salary",
    "base-pay": 3600,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|4000",
      "1749708000000|Jun 12, 2025|4800"
    ]
  }
#+end_src

**** Monthly salary

#+begin_src json :tangle requests/04-pay-structure-monthly.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Monthly Salary",
    "base-pay": 7500,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|8333",
      "1749708000000|Jun 12, 2025|10000"
    ]
  }
#+end_src

**** Annual salary

#+begin_src json :tangle requests/05-pay-structure-annually.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Annual Salary",
    "base-pay": 90000,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100000",
      "1749708000000|Jun 12, 2025|120000"
    ]
  }
#+end_src

*** Tax timing
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Tax due previous month

  This is currently calculated same way as the ~:same-month~ (value ~0~).

#+begin_src json :tangle requests/06-tax-previous-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": -1,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due same month

#+begin_src json :tangle requests/07-tax-same-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": 0,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due following month

#+begin_src json :tangle requests/08-tax-following-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": 1,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due last month of a quarter

#+begin_src json :tangle requests/09-tax-last-month-of-quarter.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": [3, 6, 9, 12],
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due month following end of a quarter

#+begin_src json :tangle requests/10-tax-month-following-end-of-quarter.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": [1, 4, 7, 10],
    "employer-tax-rate": 0.20
  }
#+end_src

*** Benefits
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Benefits paid each month

  This is currently the default behaviour.

#+begin_src json :tangle requests/11-benefits-monthly.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "benefits-payment-frequency": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "benefits-allowance": 0.33
  }
#+end_src

**** Benefits paid every quarter

#+begin_src json :tangle requests/12-benefits-quaterly.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "benefits-payment-frequency": [3, 6, 9, 12],
    "benefits-allowance": 0.33
  }
#+end_src

**** Benefits paid annually

#+begin_src json :tangle requests/13-benefits-annually.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "benefits-payment-frequency": 9,
    "benefits-allowance": 0.33
  }
#+end_src

** Staff plans
#+begin_comment
  Ministries in Orwell’s “Nineteen Eighty-Four”

  1.	Ministry of Truth (Minitrue):
  -	Responsible for propaganda, rewriting history, and ensuring that the Party’s version of events remains the only truth.
  -	Ironically, it spreads lies and fabrications.

  2.	Ministry of Peace (Minipax):
  -	Oversees war efforts.
  -	Ironically, it perpetuates continuous warfare to maintain social control.

  3.	Ministry of Love (Miniluv):
  -	Responsible for law enforcement, brainwashing, and torture.
  -	Ironically, it is a place of fear and cruelty.

  4.	Ministry of Plenty (Miniplenty):
  -	Manages the economy and ensures scarcity to keep citizens dependent on the Party.
  -	Ironically, it maintains poverty and rationing.
#+end_comment

*** Without business function

#+begin_src json :tangle requests/20-staff-plans-no-bizfn.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "staff": [
      {
        "pay-structure": "Hourly Rate",
        "base-pay": 90,
        "number-of-hires": 7,
        "benefits-payment-frequency": 9,
        "benefits-allowance": 0.33
      }
    ]
  }
#+end_src

*** One department

#+begin_src json :tangle requests/21-staff-plans.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "staff": [
      {
        "business-function": "Minitrue",
        "pay-structure": "Hourly Rate",
        "base-pay": 90,
        "number-of-hires": 7,
        "benefits-payment-frequency": 9,
        "benefits-allowance": 0.33
      }, {
        "business-function": "Minitrue",
        "pay-structure": "Hourly Rate",
        "base-pay": 60,
        "number-of-hires": 12,
        "benefits-payment-frequency": 9,
        "benefits-allowance": 0.2
      }
    ]
  }
#+end_src

* References

  - [[https://www.unixtimestamp.com][Unix timestamp online tool]].
  - [[https://fly.io/apps/patty-reports][The app deployed to Fly.io]].
