* About

#+begin_src sh
  # Run in development.
  clojure -M -m reports-api.core
#+end_src

* Deployment

  Refer to the ~Dockerfile~. You must build the uberjar prior to deployment.
  Refer to the references section below for the deployed app URL.

#+begin_src sh
  # Build the uberjar and deploy to Fly.
  clojure -T:build uber && fly deploy

  # Verify the service is running.
  curl https://patty-reports.fly.dev/api/v1/ping
#+end_src

* API

  Note that JSON keys of the request body can be either in snake_case or in kebab-case, it doesn't matter. All the response JSON keys are in snake_case.

#+begin_src sh
  # Make a request.
  curl http://localhost:8080/api/v1/reports/staff-plan --json @requests/01-base.json | jq

  # Shortcut (see .env/zsh.zsh).
  report staff-plan requests/01-base.json
#+end_src

** Staff plan
*** Minimal request

  Only required properties are provided.

#+begin_src json :tangle requests/01-base.json :mkdirp yes
  {"pay-structure": "Hourly Rate", "base-pay": 90}
#+end_src

*** Pay structure
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Hourly rate

#+begin_src json :tangle requests/02-hourly-rate.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ]
  }
#+end_src

**** Weekly salary

#+begin_src json :tangle requests/03-weekly-salary.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Weekly Salary",
    "base-pay": 3600,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|4000",
      "1749708000000|Jun 12, 2025|4800"
    ]
  }
#+end_src

**** Monthly salary

#+begin_src json :tangle requests/04-monthly-salary.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Monthly Salary",
    "base-pay": 7500,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|8333",
      "1749708000000|Jun 12, 2025|10000"
    ]
  }
#+end_src

**** Annual salary

#+begin_src json :tangle requests/05-annual-salary.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Annual Salary",
    "base-pay": 90000,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100000",
      "1749708000000|Jun 12, 2025|120000"
    ]
  }
#+end_src

*** Tax timing
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Tax due previous month

  This is currently calculated same way as the ~:same-month~ (value ~0~).

#+begin_src json :tangle requests/06-previous-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": -1,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due same month

#+begin_src json :tangle requests/07-same-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": 0,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due following month

#+begin_src json :tangle requests/08-following-month.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": 1,
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due last month of a quarter

#+begin_src json :tangle requests/09-last-month-of-quarter.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": [3, 6, 9, 12],
    "employer-tax-rate": 0.20
  }
#+end_src

**** Tax due month following end of a quarter

#+begin_src json :tangle requests/10-month-following-end-of-quarter.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "employer-tax-timing": [1, 4, 7, 10],
    "employer-tax-rate": 0.20
  }
#+end_src

*** Benefits
**** Legend

  This applies to all the following sections.

  - ~projections-start-date~: 31/12/2024.
  - ~employment-start-date~: 5/2/2025.
  - ~employment-end-date~: 5/10/2025.
  - ~pay-changes.effective-date~: 1/4/2025 and 12/6/2025.

**** Benefits paid each month

  This is currently the default behaviour.

#+begin_src json :tangle requests/11-monthly-benefits.json :mkdirp yes
  {
    "projections-start-date": 1735687848739,
    "employment-start-date": 1738735200000,
    "employment-end-date": 1759644000000,
    "pay-structure": "Hourly Rate",
    "base-pay": 90,
    "pay-changes": [
      "1743487200000|Apr 01, 2025|100",
      "1749708000000|Jun 12, 2025|120"
    ],
    "benefits-payment-frequency": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "benefits-allowance": 0.33
  }
#+end_src

* References

  - [[https://www.unixtimestamp.com][Unix timestamp online tool]].
  - [[https://fly.io/apps/patty-reports][The app deployed to Fly.io]].
